#!/usr/bin/env python3
"""Turn a Natural Earth coastline GeoJSON into the SeisMonitor globe coastline header.

Emits src/SeisCoast.h: one flat `static const float GLOBE_COAST[][2]` of {lat,lon}, with a {999,999}
sentinel between features (pen-up), plus GLOBE_COAST_N. The globe is only ~148px across and it SPINS
(re-projected every frame), so this trades invisible sub-pixel detail for speed.

LATITUDE-AWARE: the globe is an orthographic projection, so a degree of LONGITUDE spans cos(lat) of the
screen — near the poles the coastline piles up into a tiny area and 1px lines merge into a green blob.
So the simplify tolerance GROWS toward the poles (base_tol / cos(lat)); the equator/mid-latitudes keep
fine detail while the high Arctic is thinned hard. Small islands are filtered on their *screen* span
(span * cos(lat)), which drops the tiny high-lat specks that green out but keeps equatorial islands.

Usage: python tools/gencoast.py <in.geojson> <out.h> [base_tol_deg] [min_span] [min_pts] [cos_floor]
"""
import json, sys, math

def perp(pt, a, b):
    (x, y), (x1, y1), (x2, y2) = pt, a, b
    dx, dy = x2 - x1, y2 - y1
    if dx == 0 and dy == 0:
        return math.hypot(x - x1, y - y1)
    t = ((x - x1) * dx + (y - y1) * dy) / (dx * dx + dy * dy)
    t = max(0.0, min(1.0, t))
    return math.hypot(x - (x1 + t * dx), y - (y1 + t * dy))

def dp(pts, base_tol, cos_floor):
    if len(pts) < 3:
        return pts[:]
    dmax, idx = 0.0, 0
    for i in range(1, len(pts) - 1):
        d = perp(pts[i], pts[0], pts[-1])
        if d > dmax:
            dmax, idx = d, i
    lat = pts[idx][1]                                   # thin more toward the poles (screen compresses there)
    tol_i = base_tol / max(math.cos(math.radians(lat)), cos_floor)
    if dmax > tol_i:
        left = dp(pts[:idx + 1], base_tol, cos_floor)
        right = dp(pts[idx:], base_tol, cos_floor)
        return left[:-1] + right
    return [pts[0], pts[-1]]

def lines_of(geom):
    t, c = geom['type'], geom['coordinates']
    if t == 'LineString':   return [c]
    if t == 'MultiLineString': return list(c)
    if t == 'Polygon':      return list(c)
    if t == 'MultiPolygon': return [ring for poly in c for ring in poly]
    return []

def span(pts):
    xs = [p[0] for p in pts]; ys = [p[1] for p in pts]
    return math.hypot(max(xs) - min(xs), max(ys) - min(ys))

def mean_abs_lat(pts):
    return sum(abs(p[1]) for p in pts) / len(pts)

def main():
    src, out = sys.argv[1], sys.argv[2]
    base_tol  = float(sys.argv[3]) if len(sys.argv) > 3 else 0.42
    min_span  = float(sys.argv[4]) if len(sys.argv) > 4 else 2.2
    min_pts   = int(sys.argv[5])   if len(sys.argv) > 5 else 3
    cos_floor = float(sys.argv[6]) if len(sys.argv) > 6 else 0.22   # ~cos(77deg): cap how hard poles thin

    d = json.load(open(src, encoding='utf-8'))
    feats = []
    for f in d['features']:
        for line in lines_of(f['geometry']):
            pts = [(float(x), float(y)) for x, y in line]  # [lon,lat]
            if len(pts) < 2:
                continue
            eff_span = span(pts) * math.cos(math.radians(mean_abs_lat(pts)))   # SCREEN span, not raw
            if eff_span < min_span:
                continue
            s = dp(pts, base_tol, cos_floor)
            if len(s) < min_pts:
                continue
            feats.append(s)

    feats.sort(key=lambda s: -span(s))          # biggest landmasses first
    total = sum(len(s) for s in feats)

    lines = []
    lines.append("// Globe coastline - Natural Earth 1:50m, latitude-aware simplify for the ~148px spinning globe.")
    lines.append("// Generated by tools/gencoast.py. {lat,lon} pairs; {999,999} = pen-up between features.")
    lines.append("// Tolerance grows toward the poles (base/cos lat) so the Arctic doesn't green out; equator keeps detail.")
    lines.append(f"// base_tol={base_tol}  min_span={min_span}  cos_floor={cos_floor}  -> {len(feats)} features, {total} points.")
    lines.append("static const float GLOBE_COAST[][2] = {")
    for s in feats:
        lines.append("  " + "".join("{%.1f,%.1f}," % (lat, lon) for lon, lat in s))
        lines.append("  {999,999},")
    lines.append("};")
    lines.append("static const int GLOBE_COAST_N = (int)(sizeof(GLOBE_COAST)/sizeof(GLOBE_COAST[0]));")
    open(out, 'w', encoding='ascii').write("\n".join(lines) + "\n")
    print(f"{out}: {len(feats)} features, {total} coastline points (+{len(feats)} sentinels)")

if __name__ == '__main__':
    main()
